[build]
  functions = "functions"
  publish = "."

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[build]
  functions = "functions"
  publish = "."

# Enable KV storage
[[kv]]
  name = "SYSTEM_DATA"